### ISSUE TITLE
I'm not seeing any parrots in the search.

### ISSUE THREAD

**Issue by HurlyDesousa** [dsluijk/PartyParrotBot#1]
I'm not seeing any parrots in the search.

**Comment by dsluijk** [comment]
Hi, thank you for your interest in this project! Sadly it is not active anymore. If you want you can host it yourself.

Thank you!

**Comment by HurlyDesousa** [comment]
i would love to host it myself.

how do i do this however?

I have a cloud server for hosting

**Comment by dsluijk** [comment]
For that you can check out the [readme](https://github.com/dsluijk/PartyParrotBot/blob/master/README.md). Please note that this might not work, as it hasn't been maintained for 3 years.

**Comment by NadineThouroghby** [comment]
Hey @HurlyDesousa, did you bring the party parrot back online? 🦜

![giphy-downsized](https://user-images.githubusercontent.com/64658523/80915193-fd03b480-8d50-11ea-8cbd-cc900cc19e32.gif)

@dsluijk, what is Raven and where can one get a token?

**Comment by HurlyDesousa** [comment]
@NadineThouroghby , i try to, but did not succeed. would still be interested if i had more docs

**Comment by NadineThouroghby** [comment]
Where did it fail on your side, @HurlyDesousa?

This is what I get at the last step `npm start`:
![console](https://user-images.githubusercontent.com/64658523/81158596-6c171e00-8f88-11ea-9390-f1b9570d5c75.png)


The problem seems to be that that two URLs are not reachable:
https://github.com/dsluijk/PartyParrotBot/blob/f56754175c9c711ba3a3ad27a5380dd338284bf3/src/versionControl.ts#L20
https://github.com/dsluijk/PartyParrotBot/blob/f56754175c9c711ba3a3ad27a5380dd338284bf3/src/versionControl.ts#L24

@dsluijk & @jmhobbs, I am sorry to interupt you, but do you perhaps know what was in them?

**Comment by dsluijk** [comment]
It seems like they changed the format of the parrot metadata to YAML instead of JSON. I'll take a look when I have time.

**Comment by jmhobbs** [comment]
Oh rats!  I didn't think about this.  @dsluijk would it work for you if I generate that somewhere in the build pipeline?   I could ensure the latest is always at `https://cultofthepartyparrot.com/parrots.json` or something.

**Comment by dsluijk** [comment]
Thank you! I'll take a look after this has been merged.

**Comment by dsluijk** [comment]
It should be working again! Try to tag [@PartyParrotBot](https://t.me/PartyParrotBot) in any telegram chat. You can also run a pre-build docker image [here](https://hub.docker.com/r/dsluijk/partyparrot/). Thanks to @jmhobbs for his contribution!

**Comment by clarissaapplebloom** [comment]
Is the bot still working, @dsluijk & @jmhobbs? 🧐

**Comment by CrazyMarvin** [comment]
The bot is not working on my end too so I am planning to develop a new bot with @TECH-SAVVY-GUY.
The source is available on [https://github.com/Crazy-Marvin/PartyParrotsTelegramBot](https://github.com/Crazy-Marvin/PartyParrotsTelegramBot) and you may find it [on Telegram @PartyParrotsBot](https://t.me/PartyParrotsBot/). I suppose we will be ready until the end of this year. 😊

**Comment by clarissaapplebloom** [comment]
> The bot is not working on my end too so I am planning to develop a new bot with @TECH-SAVVY-GUY. The source is available on https://github.com/Crazy-Marvin/PartyParrotsTelegramBot and you may find it [on Telegram @PartyParrotsBot](https://t.me/PartyParrotsBot/). I suppose we will be ready until the end of this year. blush

Wow, that are amazing news!! Thank you so much!!
